CREATE TABLE IF NOT EXISTS agendamentos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cliente VARCHAR(100) NOT NULL,
    servico VARCHAR(50) NOT NULL,
    valor DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    data_agendamento DATE NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    horario TIME NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);